name: Run Tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
   
    - name: BuildRelease
      run: dotnet build --configuration Release **/*.sln
    - name: Test
      run: dotnet test **/*.sln --verbosity normal
